document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln(" 温馨提示：");
document.writeln(" <a style=color:white; href=\'https://www.20201314.cn\'>1314电影站</a>&nbsp;是一个提供影视大全排行榜,最新热门电影,好看的<a href=\'https://www.20201314.cn/vodtype/lianxuju/\'>电视剧</a>,成版人快手破解版,电影票房排行榜,最新热播电视剧,2021最新<a href=\'https://www.20201314.cn/vodtype/dianying/\'>电影</a>,韩国电视剧,香港TVB电视剧,国产剧,日剧,美剧,<a href=\'https://www.20201314.cn/vodtype/zongyi/\'>综艺节目</a>以及动漫在线观看的免费追剧大全电视剧网站和剧集剧情交流场所.");
document.writeln(" <a style=color:white; href=\'https://www.20201314.cn\'>20201314.cn</a>&nbsp;域名非常好记,望各位网友帮忙宣传下本站,还是原来的配方,还是熟悉的味道...");
document.writeln(" ");
document.writeln(" </div></div>");
document.writeln(" ");
document.writeln(" {include file=\'iqiyi/shouyetop\'}");
document.writeln(" <!--PC不展示-->  ");
document.writeln(" ");
document.writeln("<!--合作");
document.writeln("<div class=\'aliyun\'>");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'担保平台\'>平台担保&nbsp;<font style=color:red; size=1px;>HOT</font></h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("						     <li><a class=\'text-overflow\' style=color:white; href=\'https://www.x8x8.site\'>大人入口</a></li>");
document.writeln("						<li><a class=\'text-overflow\' style=color:red; href=\'https://www.xiuluo.ru/360baidu/yipin2.html\'>一品娱乐</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' style=color:red; href=\'https://www.xiuluo.ru/360baidu/jinniu3.html\'>金牛娱乐</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' style=color:red; href=\'https://plan.homeov.com\'>在线计划</a></li>");
document.writeln("                       ");
document.writeln("				</ul>");
document.writeln("		        	</div>									");
document.writeln("	        	</div>	");
document.writeln("	 </div></div>-->");
document.writeln("<!--end 合作-->");
document.writeln("<!--电影-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'热门电影\'>电影</h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("						  <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/xijupian\')}\' title=\'好看的喜剧片\'>喜剧片</a></li>   ");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/dongzuopian\')}\' title=\'好看的动作片\'>动作片</a></li>");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/kehuanpian\')}\' title=\'好看的科幻片\'>科幻片</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/kongbupian\')}\' title=\'好看的恐怖片\'>恐怖片</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/aiqingpian\')}\' title=\'好看的爱情片\'>爱情片</a></li>");
document.writeln("                        ");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/zhanzhengpian\')}\' title=\'好看的战争片\'>战争片</a></li>");
document.writeln("                       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/juqingpian\')}\' title=\'好看的剧情片\'>剧情片</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/jilupian\')}\' title=\'好看的纪录片\'>纪录片</a></li>");
document.writeln("                        ");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/weidianying\')}\' title=\'好看的微电影\'>微电影</a></li>");
document.writeln("                       ");
document.writeln("				</ul>");
document.writeln("		        	</div>									");
document.writeln("	        	</div>	");
document.writeln("	 </div>");
document.writeln("<!--end 电影-->");
document.writeln("<!--电视剧-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'好看的电视剧\'>电视剧</h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/guochanju\')}\' title=\'最新国产剧\'>国产剧</a></li>");
document.writeln("						 <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/xianggangju\')}\' title=\'最新香港剧\'>香港剧</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/taiwangju\')}\' title=\'最新台湾剧\'>台湾剧</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/oumeiju\')}\' title=\'最新欧美剧\'>欧美剧</a></li>");
document.writeln("                       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/rebenju\')}\' title=\'最新日本剧\'>日本剧</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/hanguoju\')}\' title=\'最新韩国剧\'>韩国剧</a></li>");
document.writeln("                        ");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/haiwaiju\')}\' title=\'最新海外剧\'>海外剧</a></li>");
document.writeln("                       ");
document.writeln("				</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end 电视剧-->	");
document.writeln("<!--综艺-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'热门综艺节目\'>综艺</h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/zongyi\')}\' title=\'热门综艺节目\'>综艺节目</a></li>");
document.writeln("                         ");
document.writeln("				</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end 综艺-->	");
document.writeln("<!--动漫-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'最新动漫\'>动漫</h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/vodtype/dongman\')}\' title=\'好看的动漫\'>动漫剧场</a></li>");
document.writeln("				</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end 动漫-->	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--art-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'热门资讯\'>热门资讯</h2>");
document.writeln("    	</div>");
document.writeln("                  <div class=\'hy-index-tags active hidden-md clearfix\'>");
document.writeln("					<div class=\'item\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("                      ");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/arttype/baoluowanxiang\')}\' title=\'包罗万象\'>包罗万象</a></li>");
document.writeln("                       ");
document.writeln("				</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end art-->	");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--排行榜-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'热门排行榜\'>排行榜</h2>");
document.writeln("    	</div>");
document.writeln("               ");
document.writeln("		<div class=\'hy-index-tags active hidden-md clearfix\'>				");
document.writeln("           <div class=\'item\'>");
document.writeln("               ");
document.writeln("                      	<ul class=\'clearfix\'>");
document.writeln("					<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/rank\')}\' title=\'电影电视剧排行榜\'>周排行榜</a></li>");
document.writeln("				");
document.writeln("						</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end 排行榜-->");
document.writeln("<!--更新榜-->");
document.writeln("<div class=\'fed-list-home fed-part-layout fed-back-whits fed-part-rows\'>");
document.writeln("	<div class=\'fed-list-head fed-part-rows fed-padding\'>");
document.writeln("		<h2 class=\'fed-font-xvi\' title=\'最新排行榜\'>最近更新</h2>");
document.writeln("    	</div>");
document.writeln("               ");
document.writeln("		<div class=\'hy-index-tags active hidden-md clearfix\'>				");
document.writeln("           <div class=\'item\'>");
document.writeln("               ");
document.writeln("                      	<ul class=\'clearfix\'>");
document.writeln("					<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newys\')}\' title=\'最新影视更新表\'>影视总榜</a></li>");
document.writeln("				<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newdy\')}\' title=\'电影更新表\'>电影榜</a></li>");
document.writeln("				<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newds\')}\' title=\'电视剧更新表\'>电视剧榜</a></li>");
document.writeln("				<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newzy\')}\' title=\'综艺更新表\'>综艺榜</a></li>");
document.writeln("                       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newdm\')}\' title=\'动漫更新表\'>动漫榜</a></li>");
document.writeln("					 <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newxj\')}\' title=\'喜剧片更新表\'>喜剧片榜</a></li>   ");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newdz\')}\' title=\'动作片更新表\'>动作片榜</a></li>");
document.writeln("						<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newkh\')}\' title=\'科幻片更新表\'>科幻片榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newkb\')}\' title=\'恐怖片更新表\'>恐怖片榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newaq\')}\' title=\'爱情片更新表\'>爱情片榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newzz\')}\' title=\'战争片更新表\'>战争片榜</a></li>");
document.writeln("                       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newjq\')}\' title=\'剧情片更新表\'>剧情片榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newjl\')}\' title=\'记录片更新表\'>纪录片榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newwdy\')}\' title=\'微电影更新表\'>微电影榜</a></li>");
document.writeln("                       	<li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newgcj\')}\' title=\'国产剧更新表\'>国产剧榜</a></li>");
document.writeln("						 <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newxgj\')}\' title=\'香港剧更新表\'>香港剧榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newtwj\')}\' title=\'台湾剧更新表\'>台湾剧榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newomj\')}\' title=\'欧美剧更新表\'>欧美剧榜</a></li>");
document.writeln("                       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newrbj\')}\' title=\'日本剧更新表\'>日本剧榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newhgj\')}\' title=\'韩国剧更新表\'>韩国剧榜</a></li>");
document.writeln("                        <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newhwj\')}\' title=\'海外剧更新表\'>海外剧榜</a></li>");
document.writeln("                       ");
document.writeln("				       <li><a class=\'text-overflow\' href=\'{:mac_url(\'/label/newzx\')}\' title=\'最新资讯更新表\'>资讯总榜</a></li>");
document.writeln("				");
document.writeln("						</ul>");
document.writeln("			</div>									");
document.writeln("		</div>	");
document.writeln("	</div>");
document.writeln("<!--end 更新榜-->");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--排行榜-->");
document.writeln("<div class=\'aliyun2\'>");
document.writeln("<div class=\'fed-part-case fed-part-rows\'>");
document.writeln("	{maccms:type num=\'27\' ids=\'2,1,3,4,6,7,8,9,10,11,12,20,21,13,14,15,16,22,23,24\' order=\'asc\' by=\'sort\' flag=\'vod\' id=\'vfed\'}");
document.writeln("	<div class=\'fed-rank-info fed-part-layout fed-part-rows fed-back-whits fed-col-sm6 fed-col-md4\'>");
document.writeln("		<div class=\'fed-list-info fed-list-rank fed-part-rows fed-padding\'>");
document.writeln("			<h2 class=\'fed-list-head fed-part-rows fed-font-xvi\' title=\'{$vfed.type_name}更新表\'>{$vfed.type_name}更新表<a class=\'fed-part-tips fed-font-xiv\' href=\'{:mac_url_type($vfed)}\'>更多</a></h2>");
document.writeln("			<ul class=\'fed-part-rows\'>");
document.writeln("				{maccms:vod num=\'10\' type=\'\'.$vfed[\'type_id\'].\'\' order=\'desc\' by=\'time\'}");
document.writeln("				<li class=\'fed-part-eone8\'>");
document.writeln("					<a href=\'{:mac_url_vod_detail($vo)}\' title=\'《{$vo.vod_name}》全集高清在线观看\'>");
document.writeln("					    <span class=\'fed-part-nums fed-part-num{$key}\'>{$key}</span>");
document.writeln("					    {$vo.vod_name|mac_filter_html}</a>");
document.writeln("					<span class=\'fed-text-muted fed-part-tips\'>{$vo.vod_remarks|mac_default=\'HD\'} {$vo.vod_time|date=\'m.d\',###}</span>");
document.writeln("				</li>");
document.writeln("				{/maccms:vod}");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	{/maccms:type}");
document.writeln("	");
document.writeln("		{maccms:type num=\'1\' ids=\'180\'  order=\'asc\' by=\'sort\' flag=\'art\' id=\'vfed\'}");
document.writeln("	<div class=\'fed-rank-info fed-part-layout fed-part-rows fed-back-whits fed-col-sm6 fed-col-md4\'>");
document.writeln("		<div class=\'fed-list-info fed-list-rank fed-part-rows fed-padding\'>");
document.writeln("			<h2 class=\'fed-list-head fed-part-rows fed-font-xvi\' title=\'{$vfed.type_name}更新表\'>{$vfed.type_name}<a class=\'fed-part-tips fed-font-xiv\' href=\'{:mac_url_type($vfed)}\'>更多</a></h2>");
document.writeln("			<ul class=\'fed-part-rows\'>");
document.writeln("				{maccms:art num=\'10\' type=\'\'.$vfed[\'type_id\'].\'\' order=\'desc\' by=\'time\'}");
document.writeln("				<li class=\'fed-part-eone8\'>");
document.writeln("					<a href=\'{:mac_url_art_detail($vo)}\' title=\'{$vo.art_name}\'><span class=\'fed-part-nums fed-part-num{$key}\'>{$key}</span>{$vo.art_name|mac_filter_html}</a>");
document.writeln("						");
document.writeln("				</li>");
document.writeln("				{/maccms:art}");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	{/maccms:type}");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<!--end 排行榜-->");
document.writeln("   {include file=\'iqiyi/shouyebuttom\'}");
document.writeln("    ");